
###Create Product
POST /v1/api/product/shop/create-product HTTP/1.1
Host: 10.56.66.52:3056
x-api-key: 4fd462e10a08d037213a5bc1e9e3daade84af371bb5873e0dd2de8f817def201c28d17fa8435c80216f7d9faabb27dcf68cfc69f6a78faa6798dc98c5e2eda5a
x-client-id: 6698edbfd7a059037907cf3a
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk4ZWRiZmQ3YTA1OTAzNzkwN2NmM2EiLCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsImlhdCI6MTcyMTM1ODU2NCwiZXhwIjoxNzIxNTMxMzY0fQ.h_W66RKWg0AbchcFrHMxuv3_LqtVLhFQGRgoXUdIy_A
Content-Type: application/json

//{
//  "product_name": "New Jeans",
//  "product_description": "High-quality denim jeans",
//  "product_price": 50,
//  "product_type": "Clothing",
//  "product_thumb": "product_thumb",
//  "product_quantity": "5",
//  "product_attributes": {
//    "brand": "Levis",
//    "size": "L",
//    "material": "Denim"
//  }
//}

//{
//  "product_name": "IPhone 14 64GB",
//  "product_description": "New Product",
//  "product_price": 500,
//  "product_type": "Electronics",
//  "product_thumb": "product_thumb",
//  "product_quantity": "5",
//  "product_attributes": {
//    "manufacturer": "Apple",
//    "model": "Ihone 14",
//    "color": "Gold"
//  }
//}